export declare const OnePanelModal: {
    width: string;
    minHeight: string;
    borderRadius: string;
    boxShadow: string;
    margin: string;
    padding: string;
    overflow: string;
};
export declare const TwoPanelModal: {
    width: string;
    minHeight: string;
    borderRadius: string;
    boxShadow: string;
    margin: string;
    padding: string;
    overflow: string;
};
export declare const OnboardingWrapper: import("styled-components").StyledComponent<"div", any, {}, never>;
export declare const OnboardHeader: import("styled-components").StyledComponent<"h1", any, {}, never>;
export declare const OnboardSubHeader: import("styled-components").StyledComponent<"h3", any, {}, never>;
export declare const OnboardInput: import("styled-components").StyledComponent<"div", any, {}, never>;
export declare const OnboardButton: import("styled-components").StyledComponent<"button", any, {}, never>;
export declare const CallToSignIn: import("styled-components").StyledComponent<"div", any, {}, never>;
export declare const OnboardDisclaimer: import("styled-components").StyledComponent<"div", any, {}, never>;
export declare const OnboardCountries: any;
export declare const ConfirmWrapper: import("styled-components").StyledComponent<"div", any, {}, never>;
export declare const ConfirmHeader: import("styled-components").StyledComponent<"h1", any, {}, never>;
export declare const MainImage: import("styled-components").StyledComponent<"img", any, {}, never>;
export declare const Separator: import("styled-components").StyledComponent<"div", any, {}, never>;
