export declare const signUp: (data: any) => Promise<any>;
export declare const signIn: (data: any) => Promise<any>;
export declare const recovery: (email: any) => Promise<any>;
export declare const changePassword: (token: any, password: any) => Promise<any>;
export declare const validateToken: (token: any) => Promise<any>;
export declare const updateToken: (token: any) => Promise<any>;
export declare const checkUsername: (username: any) => Promise<any>;
export declare const checkEmail: (email: any) => Promise<any>;
export declare const checkBlockedCountry: (countryid: any) => Promise<any>;
